#########################################################
# This file has been automatically generated by gem2tgz #
#########################################################
# -*- encoding: utf-8 -*-
# stub: timecop 0.9.1 ruby lib

Gem::Specification.new do |s|
  s.name = "timecop".freeze
  s.version = "0.9.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.require_paths = ["lib".freeze]
  s.authors = ["Travis Jeffery".freeze, "John Trupiano".freeze]
  s.date = "2017-07-05"
  s.description = "A gem providing \"time travel\" and \"time freezing\" capabilities, making it dead simple to test time-dependent code.  It provides a unified method to mock Time.now, Date.today, and DateTime.now in a single call.".freeze
  s.email = "travisjeffery@gmail.com".freeze
  s.extra_rdoc_files = ["LICENSE".freeze, "README.markdown".freeze]
  s.files = ["LICENSE".freeze, "README.markdown".freeze, "Rakefile".freeze, "lib/timecop.rb".freeze, "lib/timecop/time_extensions.rb".freeze, "lib/timecop/time_stack_item.rb".freeze, "lib/timecop/timecop.rb".freeze, "lib/timecop/version.rb".freeze, "test/test_helper.rb".freeze, "test/time_stack_item_test.rb".freeze, "test/timecop_test.rb".freeze, "test/timecop_without_date_but_with_time_test.rb".freeze, "test/timecop_without_date_test.rb".freeze]
  s.homepage = "https://github.com/travisjeffery/timecop".freeze
  s.licenses = ["MIT".freeze]
  s.rdoc_options = ["--charset=UTF-8".freeze]
  s.required_ruby_version = Gem::Requirement.new(">= 1.9.2".freeze)
  s.rubyforge_project = "timecop".freeze
  s.rubygems_version = "2.5.2.1".freeze
  s.summary = "A gem providing \"time travel\" and \"time freezing\" capabilities, making it dead simple to test time-dependent code.  It provides a unified method to mock Time.now, Date.today, and DateTime.now in a single call.".freeze
  s.test_files = ["test/test_helper.rb".freeze, "test/time_stack_item_test.rb".freeze, "test/timecop_test.rb".freeze, "test/timecop_without_date_but_with_time_test.rb".freeze, "test/timecop_without_date_test.rb".freeze]
end
